name: Sync upstream/main into vaultio

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Hourly sync

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync upstream/main to vaultio
        uses: repo-sync/github-sync@v2
        with:
          source_repo: 'bitwarden/clients'
          source_branch: 'main'
          destination_branch: 'vaultio'
          github_token: ${{ secrets.PAT }}
          sync_tags: false
